//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocId { get; set; }
        public int TableNameId { get; set; }
        public int TableRowId { get; set; }
        public string DocHRDocId_fk { get; set; }
        public string DocDesc { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<byte> DocActive { get; set; }
        public Nullable<byte> DocStatus { get; set; }
        public System.DateTime DocCreDate { get; set; }
        public string DocDabirNo { get; set; }
        public Nullable<System.DateTime> DocDabirDate { get; set; }
    
        public virtual TableName TableName { get; set; }
    }
}
