//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapRequest
    {
        public int MapRequestID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public string UrlMapDownload { get; set; }
        public string PrintTitle { get; set; }
        public string TypeSearch { get; set; }
        public string ValueSearch { get; set; }
        public string CenterPoint { get; set; }
        public string Scale { get; set; }
        public string TrackID { get; set; }
        public string OtherValue { get; set; }
    }
}
