//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageID { get; set; }
        public string MSGTablesName { get; set; }
        public string MSGOperatorKind { get; set; }
        public string MSGOperatorName { get; set; }
        public Nullable<byte> MSGKind { get; set; }
        public string MSGResult { get; set; }
        public string MSGDescription { get; set; }
        public string MSGNote { get; set; }
        public string MSGType { get; set; }
        public Nullable<byte> MSGActive { get; set; }
        public Nullable<byte> MSGStatus { get; set; }
        public string MSGCreDate { get; set; }
        public string MSGRegDate { get; set; }
        public string MSGDelDate { get; set; }
        public string MSGUserID_fk { get; set; }
    }
}
