//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NoteId { get; set; }
        public int NOTStatusId_fk { get; set; }
        public int NOTSeverityId_fk { get; set; }
        public int NOTRoleId_fk { get; set; }
        public string NOTNotifier { get; set; }
        public string NOTSubject { get; set; }
        public string NOTText { get; set; }
        public string NOTStartDate { get; set; }
        public string NOTEndDate { get; set; }
        public Nullable<int> NOTType { get; set; }
        public Nullable<bool> NOTActive { get; set; }
        public Nullable<byte> NOTStatus { get; set; }
        public System.DateTime NOTCreDate { get; set; }
        public int NOTUserID_fk { get; set; }
    
        public virtual CodeFile CodeFile { get; set; }
        public virtual CodeFile CodeFile1 { get; set; }
        public virtual User User { get; set; }
    }
}
