//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OSMEntities : DbContext
    {
        public OSMEntities()
            : base("name=OSMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OSM_ROADS> OSM_ROADS { get; set; }
    
        public virtual ObjectResult<string> sp_GeoCoding(string county, string city, string zone, string mabar1, string mabar2, string mabar3)
        {
            var countyParameter = county != null ?
                new ObjectParameter("County", county) :
                new ObjectParameter("County", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var zoneParameter = zone != null ?
                new ObjectParameter("Zone", zone) :
                new ObjectParameter("Zone", typeof(string));
    
            var mabar1Parameter = mabar1 != null ?
                new ObjectParameter("Mabar1", mabar1) :
                new ObjectParameter("Mabar1", typeof(string));
    
            var mabar2Parameter = mabar2 != null ?
                new ObjectParameter("Mabar2", mabar2) :
                new ObjectParameter("Mabar2", typeof(string));
    
            var mabar3Parameter = mabar3 != null ?
                new ObjectParameter("Mabar3", mabar3) :
                new ObjectParameter("Mabar3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GeoCoding", countyParameter, cityParameter, zoneParameter, mabar1Parameter, mabar2Parameter, mabar3Parameter);
        }
    
        public virtual ObjectResult<string> sp_ReverseGeocoding(string xY)
        {
            var xYParameter = xY != null ?
                new ObjectParameter("XY", xY) :
                new ObjectParameter("XY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ReverseGeocoding", xYParameter);
        }
    }
}
