//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public Nullable<int> ExportPlcId { get; set; }
        public Nullable<int> BirthPlcId { get; set; }
        public string CompanyName { get; set; }
        public int IsAccountOwner { get; set; }
        public string PersonMelliCode { get; set; }
        public string CompanyMelliCode { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string FatherName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string IDNo { get; set; }
        public string BirthDate { get; set; }
        public string TelNo { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public bool PersonType { get; set; }
        public System.DateTime CreDate { get; set; }
        public int UserId { get; set; }
    
        public virtual CodeFile CodeFile { get; set; }
        public virtual User User { get; set; }
        public virtual Place Place { get; set; }
        public virtual Place Place1 { get; set; }
    }
}
