//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportsID { get; set; }
        public Nullable<int> RPTParentID_fk { get; set; }
        public long RPTSystemName { get; set; }
        public string RPTTitle { get; set; }
        public string RPTAdress { get; set; }
        public string RPTSqlQuery { get; set; }
        public string RPTNote { get; set; }
        public byte RPTType { get; set; }
        public byte RPTActive { get; set; }
        public Nullable<byte> RPTStatus { get; set; }
        public string RPTCreDate { get; set; }
        public string RPTRegDate { get; set; }
        public string RPTDelDate { get; set; }
        public int RPTUserID_fk { get; set; }
    }
}
