//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestLogs = new HashSet<RequestLog>();
            this.RequestParaphs = new HashSet<RequestParaph>();
            this.RequestSignatures = new HashSet<RequestSignature>();
        }
    
        public int RequestID { get; set; }
        public int EntityID { get; set; }
        public int WorkFlowStepID_fk { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string InitialUserName { get; set; }
        public string FromUserName { get; set; }
        public Nullable<System.DateTime> FinalConfirmationDate { get; set; }
        public Nullable<int> RequestResultID { get; set; }
        public string ReciverType { get; set; }
        public string ReciverTypeValue { get; set; }
        public string ReciverOtherType { get; set; }
        public string ReciverOtherTypeValue { get; set; }
        public Nullable<bool> IsSendToSpecialUser { get; set; }
        public string SpecialUserName { get; set; }
        public Nullable<bool> Secretariat { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestLog> RequestLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestParaph> RequestParaphs { get; set; }
        public virtual WorkFlowStep WorkFlowStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestSignature> RequestSignatures { get; set; }
    }
}
