//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubSystem()
        {
            this.TableNames = new HashSet<TableName>();
        }
    
        public int SubSystemId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FarsiName { get; set; }
        public string SUBSYSEnglishName { get; set; }
        public string SUBSYSUrl { get; set; }
        public string SUBSYSIconUrl { get; set; }
        public string SUBSYSNote { get; set; }
        public Nullable<byte> SUBSYSType { get; set; }
        public byte SUBSYSActive { get; set; }
        public Nullable<byte> SUBSYSStatus { get; set; }
        public string SUBSYSCreDate { get; set; }
        public string SUBSYSRegDate { get; set; }
        public string SUBSYSDelDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableName> TableNames { get; set; }
    }
}
