//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableName()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int TablesNameID { get; set; }
        public Nullable<int> TBNParentID_fk { get; set; }
        public Nullable<int> TBSubSystemID_fK { get; set; }
        public string TBNName { get; set; }
        public string TBNPrimaryKey { get; set; }
        public string TBNNote { get; set; }
        public Nullable<int> TBNType { get; set; }
        public byte TBNActive { get; set; }
        public Nullable<byte> TBNStatus { get; set; }
        public System.DateTime TBNCreDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual SubSystem SubSystem { get; set; }
    }
}
