//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UserZones
    {
        public int UserZoneID { get; set; }
        public int USZUserId_fk { get; set; }
        public int USZZoneId_fk { get; set; }
        public string USZNote { get; set; }
        public Nullable<int> USZType { get; set; }
        public bool USZActive { get; set; }
        public Nullable<byte> USZStatus { get; set; }
        public System.DateTime USZCreDate { get; set; }
        public int USZCreateUserId_fk { get; set; }
    
        public virtual User User { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
