//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UserUnits
    {
        public int UserUnitID { get; set; }
        public int USUUserId_fk { get; set; }
        public int USUUnit_fk { get; set; }
        public string USUNote { get; set; }
        public Nullable<int> USUType { get; set; }
        public bool USUActive { get; set; }
        public Nullable<byte> USUStatus { get; set; }
        public System.DateTime USUCreDate { get; set; }
        public int USUCreateUserId_fk { get; set; }
    
        public virtual User User { get; set; }
    }
}
