//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLayerPointFeature
    {
        public int UserLayerPointFeatureId { get; set; }
        public int UserLayerPointId_fk { get; set; }
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
        public string Note { get; set; }
        public int UserId { get; set; }
    }
}
