//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserLayer()
        {
            this.USERLAYERLINEs = new HashSet<USERLAYERLINE>();
            this.USERLAYERPOINTs = new HashSet<USERLAYERPOINT>();
            this.USERLAYERPOLYGONs = new HashSet<USERLAYERPOLYGON>();
        }
    
        public int UserLayerId { get; set; }
        public int UserId_fk { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string LayerType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERLAYERLINE> USERLAYERLINEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERLAYERPOINT> USERLAYERPOINTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERLAYERPOLYGON> USERLAYERPOLYGONs { get; set; }
    }
}
