//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDev.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERLAYERPOINT
    {
        public int OBJECTID { get; set; }
        public int UserLayerPointId { get; set; }
        public int UserLayerId_fk { get; set; }
        public int MainId { get; set; }
        public string Note { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    
        public virtual UserLayer UserLayer { get; set; }
    }
}
