USE [OSM]
GO

/****** Object:  Index [IX_OSM_ROADS]    Script Date: 22/02/1400 08:50:31 ق.ظ ******/
CREATE NONCLUSTERED INDEX [IX_OSM_ROADS] ON [dbo].[OSM_ROADS]
(
	[CountyOsmId] ASC,
	[CityOsmId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



USE [OSM]
GO

/****** Object:  Index [IX_OSM_ROADS_1]    Script Date: 22/02/1400 08:50:45 ق.ظ ******/
CREATE NONCLUSTERED INDEX [IX_OSM_ROADS_1] ON [dbo].[OSM_ROADS]
(
	[CountyOsmId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


USE [OSM]
GO

/****** Object:  Index [IX_IranNode_1]    Script Date: 22/02/1400 09:20:48 ق.ظ ******/
CREATE NONCLUSTERED INDEX [IX_IranNode_1] ON [dbo].[IranNode]
(
	[CountyOsmId] ASC,
	[CityOsmId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



USE [OSM]
GO

/****** Object:  Index [IX_IranNode_2]    Script Date: 22/02/1400 09:21:01 ق.ظ ******/
CREATE NONCLUSTERED INDEX [IX_IranNode_2] ON [dbo].[IranNode]
(
	[CountyOsmId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



USE [OSM]
GO

/****** Object:  Index [IX_OSM_PLACES]    Script Date: 22/02/1400 09:25:21 ق.ظ ******/
CREATE NONCLUSTERED INDEX [IX_OSM_PLACES] ON [dbo].[OSM_PLACES]
(
	[CountyOsmId] ASC,
	[CityOsmId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
